#!/usr/bin/env bash
# This script prints "To infinity and beyond" indefinitely with
#+ a gap of 2 between each iteration.
#   Also prints "I am invincible!!!" between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible"' SIGTERM 
done
