#!/usr/bin/env bash
# This script writes "I am alive" to the file /tmp/my_process indefinitely.
#   Makes a pause of two seconds between each message.

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done