#!/usr/bin/env bash
# A script that changes localhost address on a Ubuntu server as follows:
#   - localhost changes to 127.0.0.2, while
#   - facebook.com changes to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts